import { Button, VerticalBox, LineEdit, HorizontalBox, ScrollView, ComboBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "LinkList Manager";
    min-width: 1280px;
    min-height: 720px;
    background: #f8f9fa;

    
    //Main Box
    VerticalBox {
        padding: 24px;
        spacing: 20px;

        // Header
        Text {
            text: "Linked List Manager";
            font-size: 24px;
            font-weight: 800;
            color: #1a1a1a;
            horizontal-alignment: center;
        }

        //Insert Node Section
        Rectangle {
            background: white;
            border-radius: 12px;
            border-width: 1px;
            border-color: #adadad;
            height: 210px;

            //Input Fields
            VerticalBox {
                Text {
                    text: "Insert New Node";
                    font-size: 16px;
                    font-weight: 600;
                    color: #333;
                    horizontal-alignment: center;
                }

                HorizontalBox {
                    spacing: 12px;
                    LineEdit {
                        placeholder-text: "UserName";
                        font-size: 14px;
                    }
                    LineEdit {
                        placeholder-text: "Message";
                        font-size: 14px;
                    }
                }

                Button {
                    text: "Insert Node";
                    primary: true;
                    height: 35px;
                }

                HorizontalBox {
                    spacing: 12px;
                    Text {
                        text: "Select Category: ";
                        vertical-alignment: center;
                    }
                    ComboBox {
                        model: [
                            "Insert At Beginning",
                            "Insert At End",
                            "Insert At A Position"
                        ];
                        current-index: 0;
                    }
                }
            }
        }

    }
}
