import { Button, VerticalBox, LineEdit, HorizontalBox, ScrollView, ComboBox, SpinBox } from "std-widgets.slint";

export struct Data {
    id: int,
    name: string,
    message: string,
}

export component CustomButton inherits Rectangle {
    in property <string> text;
    in property <color> base-color;
    in property <color> hover-color;
    in property <color> click-color;
    callback clicked;

    background: touch.pressed ? root.click-color : touch.has-hover ? root.hover-color : root.base-color;
    border-radius: 8px;
    border-width: 1px;
    border-color: black;

    Text { 
        text: root.text; 
        color: white; 
        font-weight: 800;
    }
    touch := TouchArea { clicked => { clicked() } }
}

export component Node inherits Rectangle {
    in property <int> id;
    in property <string> name;
    in property <string> message;

    background: white;
    border-radius: 10px;
    border-width: 1px;
    border-color: #adadad;
    width: 200px;
    height: 100px;
    drop-shadow-blur: 8px;
    drop-shadow-color: rgba(0,0,0,0.1);


    VerticalBox {
        padding: 8px;
        spacing: 0px;
        Rectangle {
            HorizontalBox {
                Text {
                    text: message;
                    font-size: 12px;
                    color: #666;
                    overflow: elide;
                }
            }
        }
        Rectangle {
            HorizontalBox {

                Rectangle {
                    background: transparent;
                    width: 30px;
                    height: 30px;
                    border-radius: 8px;
                    border-width: 1px;
                    border-color: #333;
                    Text {
                        text: id;
                        font-size: 12px;
                        font-weight: 600;
                        color: #333;
                    }
                }

                HorizontalBox {
                    Text {
                        text: name;
                        font-size: 12px;
                        font-weight: 800;
                        color: #333;
                    }
                }

                CustomButton {
                    width: 30px;
                    height: 30px;
                    text: "X";
                    
                    base-color: #ff3d3d;
                    hover-color: #ff2d2d;
                    click-color: #ff0000;
                }
            }
        }
    }
}

export component AppWindow inherits Window {
    title: "LinkList Manager";
    min-width: 1280px;
    min-height: 720px;
    background: #f8f9fa;

    property <int> insertPos;
    in property <[Data]> nodes;

    callback insert_front(Data);
    callback insert_back(Data);
    callback insert_at_pos(Data, int);
    
    //Main Box
    VerticalBox {
        padding: 24px;
        spacing: 20px;
        alignment: start;

        // Header
        Text {
            text: "Linked List Manager";
            font-size: 24px;
            font-weight: 800;
            color: #1a1a1a;
            horizontal-alignment: center;
        }
        
        //Insert Node Section
        Rectangle {
            background: white;
            border-radius: 12px;
            border-width: 1px;
            border-color: #adadad;
            height: 210px;

            //Input Fields
            VerticalBox {
                Text {
                    text: "Insert New Node";
                    font-size: 16px;
                    font-weight: 600;
                    color: #333;
                    horizontal-alignment: center;
                }

                HorizontalBox {
                    spacing: 12px;
                    usernameField := LineEdit {
                        placeholder-text: "Username";
                        font-size: 14px;
                    }
                    messageField := LineEdit {
                        placeholder-text: "Message";
                        font-size: 14px;
                    }
                }

                Button {
                    text: "Insert Node";
                    primary: true;
                    height: 35px;
                    enabled: !usernameField.text.is-empty && !messageField.text.is-empty;

                    clicked => {
                        if (insertOption.current-index == 0){
                            insert_front({
                                name: usernameField.text,
                                message: messageField.text
                            });
                        }
                        else if (insertOption.current-index == 1){
                            insert_back({
                                name: usernameField.text,
                                message: messageField.text
                            });
                        }
                        else if (insertOption.current-index == 2){
                            insert_at_pos({
                                name: usernameField.text,
                                message: messageField.text
                            }, insertPos);
                        }

                        usernameField.text = "";
                        messageField.text = "";
                        insertOption.current-index = 0;
                    }
                }

                HorizontalBox {
                    spacing: 12px;
                    Text {
                        text: "Select Category: ";
                        vertical-alignment: center;
                    }
                    insertOption := ComboBox {
                        model: [
                            "Insert At Beginning",
                            "Insert At End",
                            "Insert At A Position"
                        ];
                        current-index: 0;
                    }
                    if (insertOption.current-index == 2) : HorizontalBox {
                        Text {
                            text: "Position: ";
                            vertical-alignment: center;
                        }
                        insertPosition := SpinBox {
                            value: 0;
                            minimum: 0;

                            edited(value) => {
                                insertPos = value;
                            }
                        }
                    }
                    
                }
            }
        }

        Rectangle {
            background: white;
            border-radius: 12px;
            border-width: 1px;
            border-color: #adadad;
            height: 140px; 
            clip: true;

            ScrollView {
                HorizontalBox {
                    alignment: start;
                    spacing: 0;

                    for node[i] in root.nodes : HorizontalBox {
                        spacing: 0;
                        padding: 0;
                        alignment: center;
                        VerticalBox {
                            alignment: center;
                            padding: 0;
                            Node {
                                id: node.id;
                                name: node.name;
                                message: node.message;
                            }
                        }
                        if (i < root.nodes.length - 1) : Rectangle {
                            Text {
                                text: "→";
                                font-size: 20px;
                                font-weight: 800;
                            }
                        }
                    }
                    if (root.nodes.length > 0) : Rectangle{
                        Text {
                            text: "→NULL";
                            font-size: 20px;
                            font-weight: 800;
                        }
                    }
                }
            }
        }

        HorizontalBox {
            CustomButton {
                text: "Remove Node From Beginning";
                height: 40px;
                base-color: #ff3d3d;
                hover-color: #ff2d2d;
                click-color: #ff0000;
            }
            CustomButton {
                text: "Remove Node From End";
                height: 40px;
                base-color: #ff3d3d;
                hover-color: #ff2d2d;
                click-color: #ff0000;
            }
        }

    }
}
